### ISSUE TITLE
ToDO list

### ISSUE THREAD

**Issue by yongbinfeng** [TTU-HEP/DREAMSim#1]
- [x] implement the HPCC submission support. 
- [ ] multithreading implementation and validation
- [x] RDF implementation for plotting
- [x] track the energy leakage event by event. Sum it over if it goes outside the detector volume. Expectation is a few percent for hadron showers (and ~0 for EM showers).
- [x] allow the z value of the incoming beam to vary
- [ ] implement both Quarz fiber and plastic fiber, with one switch on the two configurations.
- [x] Add the optical output photon distribution - nPhoton as a function of radius of the fiber, maybe number of the photons and photon direction distributions. (for deciding the distance between fiber and output photon
- [x] Add Cherenkov photon polarization information

**Comment by yongbinfeng** [comment]
mostly done. multithreading would require some more work. close here.
